ip_version_priority = "ipv6"

source_urls = [
    "https://live.zhoujie218.top/tv/iptv6.txt",
    "https://live.zhoujie218.top/tv/iptv4.txt",
    "https://raw.githubusercontent.com/qingwen07/awesome-iptv/main/tvbox_live_all.txt",
    "https://cdn.jsdelivr.net/gh/YueChan/live@main/IPTV.m3u",
    "https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt",
    "https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt",
    "https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/TV-IPV4.m3u",
    "https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u",
    "https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u",
    "https://raw.githubusercontent.com/BP3388/BP001.github.io/main/tivi.list",
    "https://raw.githubusercontent.com/iptv-org/iptv/master/streams/cn.m3u",
    "https://raw.githubusercontent.com/joevess/IPTV/main/iptv.m3u8",
    "https://raw.githubusercontent.com/Supprise0901/TVBox_live/main/live.txt",
    "https://m3u.ibert.me/txt/fmml_ipv6.txt",
    "https://m3u.ibert.me/txt/ycl_iptv.txt",
    "https://m3u.ibert.me/txt/y_g.txt",
    "https://m3u.ibert.me/txt/j_home.txt",
    "https://raw.githubusercontent.com/gaotianliuyun/gao/master/list.txt",
    "https://gitee.com/xxy002/zhiboyuan/raw/master/zby.txt",
    "https://raw.githubusercontent.com/fenxp/iptv/main/live/tvlive.txt",
    "https://raw.githubusercontent.com/zwc456baby/iptv_alive/master/live.txt",
    "https://raw.githubusercontent.com/wwb521/live/main/tv.m3u",
    "http://47.99.102.252/live.txt",
    "https://raw.githubusercontent.com/vbskycn/iptv/master/tv/iptv4.txt",
    "https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u",
    "https://raw.githubusercontent.com/junge3333/juds6/main/yszb1.txt",
    "https://raw.githubusercontent.com/zzmaze/iptv/main/iptv.txt",
    "https://raw.githubusercontent.com/maitel2020/iptv-self-use/main/iptv.txt",
    "http://1805842a.123nat.com:66/agent/2.txt",
    "https://gitea.moe/Fathers/EkfkgH/raw/branch/main/yyfug.txt",
    "https://gitee.com/tushaoyong/live/raw/master/%E6%8E%A5%E5%8F%A3/IPV6.txt",
    "https://freetv.fun/test_channels_original_new.txt",
    "https://iptv-org.github.io/iptv/languages/zho.m3u",
    "https://iptv-org.github.io/iptv/countries/tw.m3u",
    "https://iptv-org.github.io/iptv/countries/us.m3u",
    "https://raw.githubusercontent.com/uc666/show/refs/heads/main/zb1.txt",
    "https://raw.githubusercontent.com/n3rddd/CTVLive/refs/heads/main/live.txt",
    "https://raw.githubusercontent.com/xiongjian83/TvBox/refs/heads/main/live.txt",
    "https://raw.githubusercontent.com/yoursmile66/TVBox/refs/heads/main/live.txt",
    "https://raw.githubusercontent.com/alienlu/iptv/refs/heads/master/iptv.txt",
    "http://tot.totalh.net/tttt.txt",
    "https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt",
    "https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/l.txt",
    "https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u",
    "https://gcore.jsdelivr.net/gh/liu673cn/box@main/libs/tv/tvlive.txt",
    "https://gitee.com/xxy002/zhiboyuan/raw/master/dsy",
    "https://gitlab.com/p2v5/wangtv/-/raw/main/lunbo.txt",
    "https://live.iptv365.org/bbxx.txt",
    "https://raw.githubusercontent.com/altn2025/iptv/main/iptv.m3u",
    "https://raw.githubusercontent.com/fenxp/iptvs/dist/live.txt",
    "https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u",
    "https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/assets/special/special.txt",
    "https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/refs/heads/main/assets/freetv/freetv_output_other.txt",
    "https://raw.githubusercontent.com/kimwang1978/TV/master/output/result.txt",
    "https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt",
    "https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u",
    "https://raw.githubusercontent.com/wwb521/live/main/tv.txt",
    "https://raw.githubusercontent.com/xzw832/cmys/main/S_CCTV.txt",
    "https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt",
    "https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u",
    "https://raw.githubusercontent.com/zzmaze/iptv/main/itvlist.txt",
    "https://live.hacks.tools/tv/iptv4.txt",
    "https://live.hacks.tools/tv/iptv4.m3u",
    "https://live.hacks.tools/tv/iptv6.txt",
    "https://live.hacks.tools/tv/iptv6.m3u",
    "https://live.zbds.top/tv/iptv4.txt",
    "https://live.zbds.top/tv/iptv4.m3u",
    "https://gh-proxy.com/raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.txt",
    "https://gh-proxy.com/raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u",
    "https://live.zbds.top/tv/iptv6.txt",
    "https://live.zbds.top/tv/iptv6.m3u",
    "https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.txt",
    "https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u",
    "https://raw.githubusercontent.com/lystv/short/main/%E5%BD%B1%E8%A7%86/tvb/MTV.txt"
]

url_blacklist = [
    "epg.pw/stream/",
    "103.40.13.71:12390",
    "[2409:8087:1a01:df::4077]/PLTV/",
    "8.210.140.75:68",
    "154.12.50.54",
    "yinhe.live_hls.zte.com",
    "8.137.59.151",
    "[2409:8087:7000:20:1000::22]:6060",
    "histar.zapi.us.kg",
    "www.tfiplaytv.vip",
    "dp.sxtv.top",
    "111.230.30.193",
    "148.135.93.213:81",
    "live.goodiptv.club",
    "iptv.luas.edu.cn",
    "[2409:8087:2001:20:2800:0:df6e:eb22]:80",
    "[2409:8087:2001:20:2800:0:df6e:eb23]:80",
    "[2409:8087:2001:20:2800:0:df6e:eb1d]/ott.mobaibox.com/",
    "[2409:8087:2001:20:2800:0:df6e:eb1d]:80",
    "[2409:8087:2001:20:2800:0:df6e:eb24]",
    "2409:8087:2001:20:2800:0:df6e:eb25]:80",
    "[2409:8087:2001:20:2800:0:df6e:eb27]"
]

announcements = [
    {
        "channel": "公告",
        "entries": [
            {"name": "请阅读", "url": "https://liuliuliu.tv/api/channels/1997/stream", "logo": "http://175.178.251.183:6689/LR.jpg"},
            {"name": "52liulian.github.io", "url": "https://liuliuliu.tv/api/channels/233/stream", "logo": "http://175.178.251.183:6689/LR.jpg"},
            {"name": "更新日期", "url": "https://gitlab.com/lr77/IPTV/-/raw/main/%E4%B8%BB%E8%A7%92.mp4", "logo": "http://175.178.251.183:6689/LR.jpg"},
            {"name": None, "url": "https://gitlab.com/lr77/IPTV/-/raw/main/%E8%B5%B7%E9%A3%8E%E4%BA%86.mp4", "logo": "http://175.178.251.183:6689/LR.jpg"}
        ]
    }
]

epg_urls = [
    "https://live.fanmingming.com/e.xml",
    "http://epg.51zmt.top:8000/e.xml",
    "http://epg.aptvapp.com/xml",
    "https://epg.pw/xmltv/epg_CN.xml",
    "https://epg.pw/xmltv/epg_HK.xml",
    "https://epg.pw/xmltv/epg_TW.xml"
]
